[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["airtable"]
  included_files = ["netlify/functions/package.json"]

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 8888
  targetPort = 3000
  framework = "#static"

[dev.environment]
  NODE_ENV = "development"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Path = {match = "^(?!.*\\.(js|css|png|jpg|svg|webmanifest)$)"}}

[context.production]
  environment = { NODE_VERSION = "18.x" }

[build.environment]
  NODE_VERSION = "18.x"

# Enable image optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true
  quality = 80
